### ISSUE TITLE
Overlapping feedback components display

### ISSUE THREAD

**Issue by refiny** [Web3Auth/Web3Auth#194]
### **Describe the bug**

A feedback component is display over wallet icon.

### **To Reproduce**

1. Login to torus
2. show wallet icon

### **Expected behavior**

there is no feedback component display.

### **Screenshots**

![image](https://user-images.githubusercontent.com/15261334/169700079-592fc4f5-2672-4955-a437-6d705a17362d.png)
![image](https://user-images.githubusercontent.com/15261334/169700088-f73e5aa0-9f69-4ef8-9611-ee6eb8c5e036.png)
![image](https://user-images.githubusercontent.com/15261334/169700097-3575816b-4b85-4851-bc34-d6049bdcd9c3.png)

### **Device Info (please complete the following information):**

- Device: Chrome
- OS: Windows 10
- Browser Chrome
- Version  101.0.4951.67
- Web3Auth Version 1.0.0

### **Additional context**

after web3auth upgrade from 1.22.6 (https://app.tor.us/v1.22.6) to 1.23.0 (https://app.tor.us/v1.23.0), this issue occured.

**Comment by refiny** [comment]
This issue also exists on your official website

![image](https://user-images.githubusercontent.com/15261334/170036547-60ed2a5e-9649-447b-b1a5-9df4977e8e28.png)

**Comment by himanshuchawla009** [comment]
Hi this issue is resolved, plz check again.

**Comment by refiny** [comment]
Till now, this issue is still in your official website and my website.
![image](https://user-images.githubusercontent.com/15261334/170412498-8427c1e2-3ceb-4e60-bbe3-a2cec57ae0f3.png)
